### ISSUE TITLE
Feature: Gtk + Adwaita app look and feel

### ISSUE THREAD

**Issue by RiemaruKarurosu** [tralph3/ZeroTier-GUI#20]
I'm currently working on a libadwaita version of the app, I need some feedback of the mockups.

![imagen](https://user-images.githubusercontent.com/45057400/227746029-492c720a-42c0-4b8b-ae19-eee1f891e7cb.png)
![imagen](https://user-images.githubusercontent.com/45057400/227746075-48e114f4-613b-45db-b781-ea1d2849261c.png)

Current Workaround of the mockups:
![imagen](https://user-images.githubusercontent.com/45057400/227746197-f9adf042-bdc8-42c7-886d-224c08f2ff90.png)
![imagen](https://user-images.githubusercontent.com/45057400/227746374-eae86120-2f68-4281-9a36-1f3b987e839f.png)

I'm not sure about what peers option do.

**Comment by tralph3** [comment]
Thanks but, since this program is nothing more than a GUI already, how is this an improvement, and not a completely different program altogether? Wouldn't it be better if you just have your own version? I'm willing to upgrade to a better framework than tkinter, sure, in fact, I had it in my plans already, but this is far too drastic to be considered just an improvement.

Anyway, if you still want to include it in this project, and if you made a fork, and not just started something completely new, then I'd advise you to open a pull request, and we can track development there ;)

**Comment by RiemaruKarurosu** [comment]
> Thanks but, since this program is nothing more than a GUI already, how is this an improvement, and not a completely different program altogether? Wouldn't it be better if you just have your own version?

Mostly for a better integratión with Gnome versions in case of GTK, I love your tkinter version, and I think I'll use your backend for the Gtk version, so, same program, different Framework. 

> Anyway, if you still want to include it in this project, and if you made a fork, and not just started something completely new, then I'd advise you to open a pull request, and we can track development there ;)

Sure!, I will open it when I have a working version, also this is my first GTK app, so, wish me luck.


Also, this will not replace tkinter version, tkinter it's better for KDE users (but QT6 could be better)

**Comment by tralph3** [comment]
Yeah well, there's not much a backend haha. This is one of my first programs and the code isn't really well structured nor separated. I wanted to rewrite this using [libzt](https://github.com/zerotier/libzt) to make it more robust and reliable, since currently it relies in running commands in the background and parsing their output, which can change at anytime and break the program. But, it still doesn't support Python 3.10, and from what I have seen, it's kinda buggy and not very well maintained, so I don't even know if I'd be better off using that.

Anyway, do feel free to do that PR and I'll take a look, I'll close this issue.

**Comment by RiemaruKarurosu** [comment]
> I wanted to rewrite this using [libzt](https://github.com/zerotier/libzt) to make it more robust and reliable,

I was checking the docs, but I think that lib doesn't provide the tools to create the actual GUI for zerotier, checking that I got up to this:

https://docs.zerotier.com/service/v1

But it requieres to read a file that needs administrator privileges, that I think basicly it's the same as sending commands ¿no?

what do you recommend?

**Comment by tralph3** [comment]
God dammit, I didn't know that existed. Well, I know what I'll use for the backend from now on. With this I can finally make a rewrite. I'll get to it when I have time, which is probably pretty soon actually.

Also, what file does it need to read? The auth token? It's easy to request access once with `pkexec` (as ZeroTier-GUI already does) and copy it to a user local directory. Then you can freely use it.

**Comment by RiemaruKarurosu** [comment]
> The auth token?

Yes, auth token (/var/lib/zerotier-one/authtoken.secret)



> `pkexec`

Taking note, thanks for the advice.
