### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by rjmalagon** [tralph3/ZeroTier-GUI#6]
Not a proper issue but not less important. Thanks for your project, is a valuable tool to study the ZeroTier-one API and to ease self owned controller networks.

And to waste no more this issue space, you can reach me when you add localization to your project. I can help with American Spanish translation.

**Comment by tralph3** [comment]
Hi, thank you for the kind words. I'm glad to hear it helped you. Also thank you for offering translating the project but I have no plans for that currently since it's a pretty small tool, and also I wouldn't have trouble translating to Spanish since I'm from Argentina :)

In fact, you can see my most recent repo, I'm currently working on a Spanish translation for a game. Nevertheless, thanks.

**Comment by Can202** [comment]
me too, the best thing that i found in Github

**Comment by tralph3** [comment]
I guess I'll close this issue since it really ain't one, but I welcome thank messages of course. I'm trying to package this to the AUR, I'm close but not quite there yet, having some trouble. Expect it pretty soon tho!
