### ISSUE TITLE
Botón para encender o apagar ZeroTier

### ISSUE THREAD

**Issue by fgarcd03** [tralph3/ZeroTier-GUI#7]
Hola, como sugerencia estaría bien poner un botón para activar o desactivar el servicio de ZeroTier, en vez tener que hacer cada vez:
`systemctl start zerotier-one `
`systemctl stop zerotier-one `

**Comment by tralph3** [comment]
Hi, I'd rather keep the issues and PRs in english so everyone can understand it. As for the suggestion, you can kinda do it by disabling networks, but I'll probably implement this too. I'll make a quick modification right now so you can have it from the py script if you want, but I'll change the GUI in the future so that it uses ttk's treeview, instead of my custom made one, I didn't realized it even existed when I made it. That will be when it makes it into a new release.

**Comment by tralph3** [comment]
Added

**Comment by fgarcd03** [comment]
Thank you!, I have tried it and it works. The only thing I would change would be to remove the message at the beginning if you don't have the service activated, as it doesn't make sense if you can activate the service in the programm itself.

**Comment by tralph3** [comment]
I don't see why it wouldn't make sense to have a message saying the service isn't active, it's fine to me. But as you might have noticed, I did hack this together in 5 minutes. I'll make more considerations later. So yeah, TODO.

**Comment by fgarcd03** [comment]
I know, but the programm won't open if that message comes up.

**Comment by tralph3** [comment]
Oh... true. I forgot I added that check lol.
